### ISSUE TITLE
Better Cube URLS

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#111]
As a user, I would like cube URLS that aren't a massive hex string.

Create an extra field in the cube DB schema for a short URL, have it default to an incrementing (hex?) numerical value, and have it be overridable to any string in cube overview. (e.g. /gwenscube)

**Comment by lane-eden** [comment]
Instead of hex the short URL should be base36 (which is representable using A-Z and 0-9). This way the url will stay very short and easy to remember even if we have a large number of cubes (up to ~1.7M cubes will fit in four base 36 digits).

Additionally, the override value should be a separate field in the DB. This way if you tell people the short URL and then later add an alias, the short URL will still work. Plus if you later remove your alias we need to know what the short URL used to be, so we need both anyway.

Lastly, I think we should limit cube URL alias character to A-Z, a-z, 0-9, _, and -. This way we don't have to worry about URL encoding.

**Comment by SeanmanX** [comment]
Potentially of interest: [mongoose-url-slugs](https://www.npmjs.com/package/mongoose-url-slugs)

**Comment by lane-eden** [comment]
Added in #238
