### ISSUE TITLE
Export Only Selected Cards

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1157]
When I export list, I'd love for it to only export the cards that I've filtered, rather than the whole list. or have some toggle that lets me choose whether to export the whole list or my current subset.

**Comment by Llannetta** [comment]
I'd very much enjoy this enhancement because I have a specific use case that would benefit from this: a partner Smashup "cube" where you combine two sets of cards to create a deck. Exporting a subset of cards from the cube would make my life a lot easier!

[cEDH Smashup Cube](https://cubecobra.com/cube/list/smashup)
