### ISSUE TITLE
Sort and filter by untagged

### ISSUE THREAD

**Issue by APillowEdwards** [dekkerglen/CubeCobra#1165]
**What would you like to be able to do?**
View cards that are untagged in a seperate column when sorting by tags, potentially being able to filter using something like `tag:""`.

For a few of of my cubes I want every card to have a tag, and when just one is missing a tag it is quite time-consuming to find which card it is.

**Comment by dekkerglen** [comment]
`tag:""` wouldn't make sense, we should instead add something like `numtags=0`

**Comment by mikeymischief** [comment]
In addition to these features, being able to use "untagged" for setting up custom draft would be welcome.

I know many users that have a "core" cube and then draft "modules". This is done today by tagging all cards in the "core" module and then tagging each module independently. The issue is that each user has to remember anytime they change the cube to tag the new cards in the "core" module.

**Comment by ruler501** [comment]
You can search tags by count so tags=0 finds cards with no tags
