### ISSUE TITLE
Markdown when editing Overview

### ISSUE THREAD

**Issue by SeanmanX** [dekkerglen/CubeCobra#126]
**What would you like to be able to do?**
As a user, I would like to utilize markdown when interacting with certain text fields (likely the body of blog posts or the cube description). 

**Describe how you would use the feature**
When editing the cube overview or creating a blogpost, I would like to be able to utilize [markdown](https://www.markdownguide.org/basic-syntax "Basic Syntax of Markdown") to better template updates. Markdown is a very powerful tool that would make any blogpost or description shine. 

**Additional context**
We would most likely be touching `texteditor.js` and `blog.js` and some of the `.pug` files in the directory
There seem to be [several](https://github.com/sparksuite/simplemde-markdown-editor "Simple MDE") [open](https://github.com/NextStepWebs/simplemde-markdown-editor "editor.md") [source](https://github.com/markdown-it/markdown-it "markdown-it") libraries we can use.

Ideally, we can just add a dependency for one of the libraries listed above.
After doing some preliminary research, `markdown-it` looks nice.

**Comment by omnihound** [comment]
@dekkerglen this would also address #114 I think

**Comment by emmett9001** [comment]
I'm interested in working on this. FWIW `markdown-it` seems like the way to go. I don't think we want to start out with a full-featured editor. Simply parsing markdown from a plaintext field is enough for an MVP.

**Comment by emmett9001** [comment]
Looking into this a bit more, I'm not certain what the benefit is. The input field already allows basic text formatting. Including images via markdown is probably a nonstarter since it requires storage, and hyperlinks in descriptions might not be worth the switch. What do you see as the specific benefits of integrating markdown over the existing input field?

**Comment by SeanmanX** [comment]
Looking for advanced formatting and embedding links.
Images would be nice but I agree that it would have a significant impact in storage

The basic formatting is not very robust at all in my opinion

**Comment by jwallra** [comment]
The current editor doesn't seem to support line breaks either.  It might be possible because in the dev blog it seems like they are rendered properly, but whenever I put new lines in the editor it generates extra divs like so, and doesn't render them:

![image](https://user-images.githubusercontent.com/13154238/65392538-deedc480-dd2a-11e9-85ae-2ef51606eee8.png)

I'm trying to import my blog posts from CT but I don't think I'll do it until I can figure out how to do proper line breaks / paragraphs.
