### ISSUE TITLE
CSV Export Sort

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#14]
As a user, I would like the CSV export to be sorted.

The CSV export should sort the cards my Color -> CMC -> Alphabetical, and then generate the export.

**Comment by ruler501** [comment]
Allowing customized sorts in the vein of #509 would be a helpful extension of this.

**Comment by dekkerglen** [comment]
I think #509 is completely different. This is calling for a static sort for csv exports, but #509 calls for a the ability to define new sorts completely.

**Comment by ruler501** [comment]
I was more mentioning that if the work there got done we could add it onto this to allow more options in the future. I wasn't thinking of it as something to be done alongside #509 or as a requirement for this, more of a stretch goal.

**Comment by dekkerglen** [comment]
This feature becomes a lot bigger if we allow sorts selection, I was thinking of just having a static sort as described in the OP. If we want to be able to choose the sort we would need to build some UI for that, and I would remove the 'good first issue' tag

**Comment by bramleyjl** [comment]
I'l look into this since it seems relatively simple and I'm just contributing for the first time. After this is taken care of I'd also be in a much better spot to take on #509 since I'll be more familiar with that area of the codebase.

**Comment by bramleyjl** [comment]
My initial take on this was to implement Color -> CMC -> Alphabetical, but it doesn't seem like it would be too much more difficult to include the current primary and secondary sorts that the user is seeing on the frontend and passing them in as parameters to the download call so that the downloaded .csv looks the same as the list that appears on the frontend.

Is that functionality we'd like to add instead of a hardcoded sort? If so should that be opened as a separate issue?
