### ISSUE TITLE
Enable Opening Cubes in a New Tab

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1689]
**What would you like to be able to do?**
Have the option to open a cube in a new tab from a profile page. The default should still be in the same tab. 

**Describe how you would use the feature**
Open multiple cubes at once without having to navigate back to the profile in between.

**Comment by dekkerglen** [comment]
This is mainly due to us hardcoding the event in the `CubePreview` object. This issue exists with all the preview objects: `DeckPreview`, `ArticlePreview`, etc. We instead need to let the browser do the work, with a href

This issue offers a good solution: https://github.com/dekkerglen/CubeCobra/issues/1614
