### ISSUE TITLE
Deleting All Text From the Cube Overview Field Inserts the Default Text

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1690]
When editing a cube overview (at least on mobile, haven't tried browser yet) and I delete all the placeholder text so I can start typing the description it reinserts the placeholder text. This causes me to have to leave part of the placeholder text while I start writing the description and need to remember to delete it later.

**Comment by lunakv** [comment]
Can confirm the issue exists on desktop browsers.

**Comment by dekkerglen** [comment]
This happens because the `cube` schema contains two fields for description, one is html that the WYSIWYG editor used, and the other is plaintext. We migrated from plaintext to WYSIWYG, and then back with the markdown update. The solution to this issue is better handling these two fields. There was a one-shot script run to eliminate the html field (and convert to markdown), so we could actually just remove that field completely.
