### ISSUE TITLE
Notifications for @'ing a user

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1691]
Our markdown parser parses `@dekkaru` and creates a tag to that user. It would be nice to get notifications when someone tags you in a comment/blog post/cube description

**Comment by lunakv** [comment]
As mentioned in #1727, the best way to do this (that I can see) is taking the new markdown parser (#1688) with our `userlink` extension and extracting all user mentions from there.
We should consider whether we want the notifications to show only from the original comment/post, or if we also want them to appear when a user mention is introduced in an edit. This feature is optional for comments, posts, and articles, but crucial to cube overviews, where editing is the only way to introduce a user mention. We'd most likely need some new database structures for this, since we wouldn't want a user to be spammed with notifications each time someone makes an edit.
