### ISSUE TITLE
Comprehensive Analysis

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#19]
As a user, I would like more options to slice my cube list's data in the analysis tab.

Here is an example of the kinds of data that would be useful: https://docs.google.com/spreadsheets/d/1s1BD4797XT--pDm_ZfJiDsnxIz_0DDx1b7rsbHHD1fk/edit

**Comment by pozz94** [comment]
I would really like to see the average CMC of the cube and the average CMC of each color.
It would also be nice to have it visualized together with the mana curve and a pie chart of the type breakdown on the same page without having to switch between different sections of the analysis data

**Comment by RKelln** [comment]
As a user I would really like to know the percentage of the different types of cards regardless of the total number of cards in each color.

Add percentage to the totals on the Type Breakdown stats tab. (Preferably leaving 0 and perhaps 1 card values without any percentage to reduce clutter). Round to 1 decimal place?

**Comment by ruler501** [comment]
I can take this up. Would probably do best to do a series of PRs that only add a few things at a time since this should be able to be broken up quite a bit.

One possible architecture that would allow users to add their own functions would be a web worker system. That should isolate the user provided scripts and prevent adding extra load to the server, though I don't fully know all the security implications and would appreciate feedback. Eventually could have sharable functions, kind of like roll20 does with scripts. For a first iteration giving web workers a few query callbacks/messages, potentially just a callback/message that takes a string query like the web ui and gives back to the script a json list of matching cards and one to submit the final display string or html.

**Comment by dekkerglen** [comment]
It's probably better just to use our tags + filters that we already have built to be able to slice the data onto different types of charts/tables in a flexible way.

I would also recommend against this as a first issue, maybe try one with the 'good first issue' tag to get started and learn the codebase a bit before taking on such a huge undertaking

**Comment by ruler501** [comment]
I put together a rough proof of concept of one way to do user customizable analytics. Can test it out at https://cubecobra.ruler501.com/cube/analysis/packwars and the code is https://github.com/ruler501/CubeCobra/tree/webworker-analytics only supports tables at the moment, but graphs should be relatively easy to add next if this is a path that's deemed promising.

**Comment by roborocket** [comment]
I think that in the curve tab on the analysis page there should be two separate graphs that break down creature and non-creature counts along the curve. It's a little misleading to think that my black section is basically the lowest curve just because I have a bunch of two-drop spot removal spells in that color. Alternatively, the ability to filter by more than just color in that page would be helpful, but breaking down creature versus non-creature curves should be a priority.
