### ISSUE TITLE
Easy Add Cycles

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#213]
As a user, I would like to easily be able to add common cycles, like lands.

Just, a button that allows one to add certain land cycles, or other commonly cubed cycles

**Comment by purxiz** [comment]
Can you assign this to me?

**Comment by emmett9001** [comment]
Is there a viable definition of a "cycle" that can be used for this purpose? It seems like kind of a nebulous concept since cycles don't necessarily have any metadata properties (CMC, name, power/toughness, etc) in common.

**Comment by purxiz** [comment]
I was only going to add land cycles, which are pretty well defined. I don't
think other cycles are commonly cubed.

**Comment by emmett9001** [comment]
Seems fine to start this with an option for "shocklands, fetchlands, abu duals, fastlands, etc". Some other common cycles in cubes are the Swords (Sword of War and Peace, Feast and Famine, etc), Forces (Force of Vigor, Force of Negation, Force of Valor), Titans (Frost Titan, Sun Titan, etc), Signets (Izzet Signet, Dimir Signet, etc), Moxen (Mox Emerald, Mox Jet, etc), and Eldrazi Titans (Emrakul, the Aeons Torn, Kozilek, Butcher of Truth, etc).

**Comment by mvhsbball22** [comment]
Does it make sense to have this exist as a separate entity like a 'cube'
that people could add cards to and save? Then a user could visit the
'Cycles' page which could be sorted by things like "Frequency", "Cost",
etc.?

Doing it this way would fit into the social goals because people could
"star" cycles they liked.  It also avoids the problem of having card-like
metadata -- in fact, the metadata would be much closer to the cube object.

**Comment by purxiz** [comment]
I'd rather they be two separate features. I'd like this feature request to
cover basically all the land cycles, and maybe some other generic cycles as
the commenter above mentioned, then we can maybe add a "modules" feature
for what you're implying. Personally, I'd rather keep any baked-in feature
to just lands, since basically every cube has lands, where as most cubes
(to the best of my knowledge) incomplete card cycles are more common than
complete ones.

I actually really like the modules idea though, and I think I'll work on it
next if you submit an issue

**Comment by ruler501** [comment]
From discord discussion today on potential ideas for this:

> have it be packages not just cycles, things like power nine, rainbow lands, etc
> have a user voting system
> allow adding packages to vote on and they get added to the main list when they cross a certain vote threshold
> allow sorting by number of votes
> allow searching for all packages that include cards matching a filter
> have them be a separate page like cards are now with the ability to add from that page
> have admins have to approve new cycle additions
