### ISSUE TITLE
Duplicate cards not being correctly handled

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#404]
I haven't replicated this yet, but several users have reported buggy behavior with duplicate cards such as:
Tagging a duplicate card propagates to the other duplicate
Only one custom image can be used for each card name

**Comment by phulin** [comment]
I think we might want to batch fixing this with an overhaul of how some of the client-side global state works, as it seems to be getting messed up in a couple places.

**Comment by phulin** [comment]
I haven't been able to reproduce the tagging bug in current master.

The issue with custom images is due to the way we stick `display_image` into `card.details`, which I believe is getting inadvertently copied into Node's in-memory carddb. I think that's what is causing the issue. Ultimately, there is no reason to store that variable rather than computing it every time, but that will require significant changes. I have a PR ready to go but am holding for next release (and hopefully it will be obsoleted by pulling more stuff into react).
