### ISSUE TITLE
Basic Land Choice

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#72]
As a user, I would like to be able to choose the basic lands available for deckbuilding.

**Comment by mgrinshpon** [comment]
As I'm glancing around the code, it looks like the function `getBasics: function(carddb)` in `serverjs/cubefn.js` needs to be overloaded to be `getBasics: function(cube, carddb)` with a default passed in. Then there's the UI work of actually specifying it and the DB work of actually saving it.

**Comment by dekkerglen** [comment]
Yes, this might seem like a small feature but there is a lot of work necessary to get it to work currently.

**Comment by Balkmeister** [comment]
Make sure you can select snow basics and wastes aswell.

**Comment by ruler501** [comment]
Wastes is handled by #1342

**Comment by roborocket** [comment]
Any suggestions on where to start on this? I'm not sure where the user-picked default would be stored and then called up from - as part of the Edit Overview modal, maybe? Options for default and customize, with five inputs for plains, island, swamp, mountain, and forest, to input set and card number so that it can be pulled from the `carddb` when customize is selected. If stored in the overview data, can that be called up in the `get basics` function?

**Comment by dekkerglen** [comment]
I wouldn't even be that restrictive with it. I would say there can be any number of 'free' cards, but the default is 5, one for each basic land.

Start with adding the field `basics` to the cube schema: https://github.com/dekkerglen/CubeCobra/blob/master/models/cube.js
Make sure there it is required and there is a default value. The type should be the same as cards in the list, as we want to be able to override the image for these cards.
When a cube is created, make sure to populate these fields.
Then, build the UI, I think 'list' would be easiest, but you can do it in edit overview as well. This UI should have the ability to remove cards from the list, add new ones, and edit current ones. If the list is empty (old cubes), have the default be the 5 basics we currently offer to be consistent.
Add an API route to save the basics.
Every time there is a new draft (search for `new Draft` and `new GridDraft`), make sure to populate the correct basics for that cube. 
That should be it, as we already built the logic for handling the basics in the deckbuilder from the draft object

**Comment by 0nderzeeboot** [comment]
I imagine the recent additions of Kaldheim have made snow more popular. At the very least, Arcum's Astrolabe is in well over a 1000 cubes.
Also, someone in my own cube circle recently proposed a cube with the blue duals in the basic land box instead of basics, effectively making blue colorless, and honestly that sounded like a gorgeous idea for a cube that I want to try out!

I guess I just wanted to let you know this feature would still very much be appreciated! :)
