### ISSUE TITLE
Custom draft format - predetermined cards

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#838]
This is probably pretty niche, but could we get an option on custom draft formats to start a players pool with a predetermined set of cards? In our Commander Cube, every player starts with a Command Tower and Arcane Signet in their pool

Posted in proxy for 'zachtib' on discord

**Comment by phulin** [comment]
I think you can just do this with a custom draft format

**Comment by ruler501** [comment]
Would be nice to have an easier UI for it so it's more discoverable. Maybe include an example that shows `name:Command Tower` as a possibility.

**Comment by RKelln** [comment]
Yes, once filtered custom drafts come in easiest way is to make a single card per pack and use `name:"Command Tower"` and add 8 to the cube. This breaks down a bit since with less players extra command towers would still be draftable unless you force it by doing something like: `name!="Command Tower"` for every other card (ugh). So, ya, might be a good future feature to allow players to start with specific cards so that it is more flexible for various numbers of players.

**Comment by dekkerglen** [comment]
No, what this feature is asking for is a special pack that is auto-drafted into each players pool. That way those cards don't circulate in the draft, and everyone had the same number

**Comment by RKelln** [comment]
Ya the above will be the workaround until it can be added. I think this is a good new feature, to keep auto-draft cards out of the cube list (or specially noted but not otherwise draftable).

**Comment by ruler501** [comment]
I think that the sealed pack feature that I've been working on solves this nicely. You create a sealed pack using the name filter syntax then users see the pack and can click to draft all the cards at once.
