### ISSUE TITLE
MongoDB Presets

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#92]
As a developer, I want to have some preconfigured data in my database after running the initial setup steps.

This can be accomplished by one of:
-  use mongodb's import/export feature, and have a pre-configured DB exported into a separate linked repo. 
- Or, we could include a script that populates some fixed values into the DB

**Comment by swood456** [comment]
I'll work on this

**Comment by crookedneighbor** [comment]
@swood456 how's the progress on this? Was just thinking this project could use a good populate db script when I found this issue.

**Comment by swood456** [comment]
Wow I completely forgot about this. I had gotten [node-mongo-seeds](https://www.npmjs.com/package/node-mongo-seeds) set up and working but had a bit of issue pulling out the formatted data. I had made some progress and should be able to have it set up and working today

**Comment by crookedneighbor** [comment]
The one suggestion I’d have about this is to use the mongoose models rather than importing data via the seeds module you posted. That will allow the seed script to remain up to date when new fields with defaults are added, or new validation rules are added. 

Node-mongo-seeds will work, but will require more work to keep it synced up with the mongoose models. 

Ultimately though, do whatever the maintainers of the project want to do. Just giving my 2 cents about it :)

**Comment by swood456** [comment]
I see what you're saying, I got this set up with [mongoose-seed](https://www.npmjs.com/package/mongoose-seed) instead so it should have validation done via mongoose. PR: https://github.com/dekkerglen/CubeCobra/pull/309

**Comment by crookedneighbor** [comment]
👏 👏 👏
